import React from "react";
import styles from "../../../styles/user.module.css";
import MarketplaceEntry from "../../MarketplaceEntry";

const Card1 = () => {
  return (
    <div>
       <div className={styles.card1main}>
       <div className={styles.fullpage}>
        <div className={styles.marketplace}>
            <h1 className={styles.title}>Marketplace</h1>
            <div className={styles.marketplace_inner}>
                <MarketplaceEntry data={{token:"ECO", 
                    desc:"ECO is a Ethereum-based token that can be used to convert to other carbon tokens on our platform.", img:"/images/logo.png"}}></MarketplaceEntry>
                <MarketplaceEntry data={{token:"MCO2", 
                    desc:"MCO2 is a Ethereum-based token backed by 1 carbon tonne by Moss.earth. It primarily focuses on obtaining credits generated by projects in the Amazon Basin.", img:"/images/mco2.png"}}></MarketplaceEntry>

                <MarketplaceEntry data={{token:"TCO2", 
                    desc:"TCO2 is a Polygon-based token backed by 1 carbon tonne from Toucan.earth. It ensures increased transparency by attaching carbon project metadata with each token.", img:"/images/tco2.png"}}></MarketplaceEntry>

                <MarketplaceEntry data={{token:"KILMA", 
                    desc:"KILMA is a Ethereum-based token backed by 1 carbon tonne in the KilmaDAO Treasury.", img:"/images/kilma.png"}}></MarketplaceEntry>
            </div>
        </div>
    </div>
        </div>
    </div>
  );
};

export default Card1;