import { ThirdwebProvider } from "@thirdweb-dev/react"
import { AppProvider } from '../../contexts/AppContext';
import Navbar from "../../components/navigation/Navbar";
import styles from "../../styles/user.module.css";
import UserHoldings from "../../components/UserHoldings";
import MarketplaceEntry from "../../components/MarketPlaceEntry";
import { getAuth } from "firebase/auth";

const activeChain = 'ethereum';
const clientid = require("./keys.json")["client-id"];

const UserProfile = () => {
    const user = getAuth().currentUser;
    return (
        <ThirdwebProvider activeChain={activeChain} clientId={clientid}>
            <AppProvider>
                <Navbar></Navbar>
                <div className={styles.fullpage}>
                    <div>
                        <div className={styles.infobox}>
                            <h1 className={styles.title}>My Profile</h1>
                            <p><b>Username :</b> {user.displayName}</p>
                            <p><b>Email :</b> {user.email}</p>
                        </div>
                        <div className={styles.holdingbox}>
                            <div className={styles.titlebox}>
                                <h1 className={styles.title}>My Holdings</h1>
                            </div>
                            <div>
                                <UserHoldings></UserHoldings>
                            </div>
                        </div>
                    </div>
                    <div className={styles.marketplace}>
                        <h1 className={styles.title}>Marketplace</h1>
                        <div className={styles.marketplace_inner}>
                            <MarketplaceEntry data={{token:"MCO2", 
                                desc:"MCO2 is a Ethereum-based token backed by 1 carbon tonne by Moss.earth. It primarily focuses on obtaining credits generated by projects in the Amazon Basin.", img:"/images/mco2.png"}}></MarketplaceEntry>
        
                            <MarketplaceEntry data={{token:"TCO2", 
                                desc:"TCO2 is a Polygon-based token backed by 1 carbon tonne from Toucan.earth. It ensures increased transparency by attaching carbon project metadata with each token.", img:"/images/tco2.png"}}></MarketplaceEntry>

                            <MarketplaceEntry data={{token:"KILMA", 
                                desc:"KILMA is a Ethereum-based token backed by 1 carbon tonne in the KilmaDAO Treasury.", img:"/images/kilma.png"}}></MarketplaceEntry>
                        </div>
                    </div>
                </div>
            </AppProvider>
        </ThirdwebProvider>
    )
}

export default UserProfile;